language: node_js
addons:
  firefox: "47.0"
node_js:
  - "6"
matrix:
  fast_finish: true
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
env:
  - TESTFOLDER=.
  - TESTFOLDER=addons/Dexie.Observable/
script:
  - npm run build release
  - cd $TESTFOLDER
  - pwd
  - bash travis.sh
